### PR TITLE
medStatusBar become threadsafe to prevent crash V4

### LINKED ISSUE #751: medStatusBar no thread-safe crash
medStatusBar contains 2 lists of messages (visible and hide).
If 2 threads or more change one of these list in same time, medInria can crash.

I detect this crash (it no just a code review) during importe many dicom series from a PACS and resize medInria window to a smallest size in the same time.
The signal shrinks the list of visible messages and grow-up the hide list, but the transfert from an to an other can conflict with life duration of a message.

**The crash is rare**

### PR DESCRIPTION
**Pull request by Florent2305**
Fix #751

### CODE REVIEW

File: src/layers/legacy/medCoreLegacy/gui/commonWidgets/medStatusBar.cpp [hunk 1]
```diff
@@ -14,18 +14,24 @@
...
+    QList<medMessage *> hiddenMessageList; // storing messages waiting to be displayed
+    QList<medMessage *> messageList;       // storing displayed messages
 };
 
 medStatusBar::medStatusBar ( QWidget* parent ) : QStatusBar ( parent ), d ( new medStatusBarPrivate )
 {
-    d->statusBarLayout = nullptr;
-    this->statusBarWidth = this->size().width();
-    this->availableSpace = -1; //value before initialization (after, always positive)
+    d->statusBarLayout = NULL;
```
Comment (mathildemerle) [inline src/layers/legacy/medCoreLegacy/gui/commonWidgets/medStatusBar.cpp:32]: beware of the NULL regression

Comment (Florent2305) [reply src/layers/legacy/medCoreLegacy/gui/commonWidgets/medStatusBar.cpp]: done

**Review by mathildemerle — APPROVED** [review]
