### PR TITLE
fix bug "Filtering process creation without process #408"

### LINKED ISSUE #408: Filtering process creation without process
Into "new" filtering workspace.
If at least one filter exist and you change "Process Type" then "Process" combobox is set to "None selected" but you can create a process

### PR DESCRIPTION
**Pull request by Florent2305**
fix #408

### CODE REVIEW

File: src/app/medInria/areas/workspaces/filtering/medFilteringWorkspace.cpp [hunk 1]
```diff
@@ -449,6 +450,9 @@ void medFilteringWorkspace::setProcessType(int index)
     d->morphoMathsVector.clear();
     d->arithmeticsVector.clear();
 
+    if (index == 0)
+    return;
```
Comment (mathildemerle) [inline src/app/medInria/areas/workspaces/filtering/medFilteringWorkspace.cpp]: there is an indentation problem here

Comment (Florent2305) [reply src/app/medInria/areas/workspaces/filtering/medFilteringWorkspace.cpp]: it's  done
