### PR TITLE
medStatusBar become threadsafe to prevent crash V3.1.x

### LINKED ISSUE #751: medStatusBar no thread-safe crash
medStatusBar contains 2 lists of messages (visible and hide).
If 2 threads or more change one of these list in same time, medInria can crash.

I detect this crash (it no just a code review) during importe many dicom series from a PACS and resize medInria window to a smallest size in the same time.
The signal shrinks the list of visible messages and grow-up the hide list, but the transfert from an to an other can conflict with life duration of a message.

**The crash is rare**

### PR DESCRIPTION
**Pull request by Florent2305**
fix #751

### CODE REVIEW

File: src/layers/legacy/medCoreLegacy/gui/commonWidgets/medStatusBar.cpp [hunk 1]
```diff
@@ -14,18 +14,25 @@
...
 };
 
 medStatusBar::medStatusBar ( QWidget* parent ) : QStatusBar ( parent ), d ( new medStatusBarPrivate )
 {
     d->statusBarLayout = NULL;
-    this->statusBarWidth = this->size().width();
-    this->availableSpace = -1; //value before initialization (after, always positive)
+    d->statusBarWidth = this->size().width();
+    d->availableSpace = -1; //value before initialization (after, always positive)
+    d->listsofMsgMutex;
```
Comment (ocommowi) [inline src/layers/legacy/medCoreLegacy/gui/commonWidgets/medStatusBar.cpp:35]: Heu ca sert a rien cette ligne la non ?

File: src/layers/legacy/medCoreLegacy/gui/commonWidgets/medStatusBar.cpp [hunk 2]
```diff
@@ -147,34 +157,42 @@ void medStatusBar::removeMessage ( medMessage* message )
...
 */
 void medStatusBar::showHiddenMessage()
 {
-    if(!this->hiddenMessageList.isEmpty())                         // if message waiting to be displayed
+    d->listsofMsgMutex.lock();
+    if(!d->hiddenMessageList.isEmpty())                         // if message waiting to be displayed
     {
-        medMessage* messageToShow = hiddenMessageList.takeFirst();
+        medMessage* messageToShow = d->hiddenMessageList.takeFirst();
+        d->listsofMsgMutex.unlock();
```
Comment (ocommowi) [inline src/layers/legacy/medCoreLegacy/gui/commonWidgets/medStatusBar.cpp:181]: Le unlock peut etre en dehors du if, tu le fais de toutes facons

File: src/layers/legacy/medCoreLegacy/gui/commonWidgets/medStatusBar.cpp (hunk 1 above)
Comment (Florent2305) [reply src/layers/legacy/medCoreLegacy/gui/commonWidgets/medStatusBar.cpp:35]: ha oui carrément c'était juste pour un point d’arrêt durant la mise au point, je vais le supprimer.

File: src/layers/legacy/medCoreLegacy/gui/commonWidgets/medStatusBar.cpp (hunk 2 above)
Comment (Florent2305) [reply src/layers/legacy/medCoreLegacy/gui/commonWidgets/medStatusBar.cpp:181]: Hélas, pas du tout, car l'appel à `addMessage(messageToShow);` ligne 168|182 lock le mutex et dans ce cas il y a deadlock.

File: src/layers/legacy/medCoreLegacy/gui/commonWidgets/medStatusBar.cpp [hunk 3]
```diff
@@ -135,8 +143,10 @@ void medStatusBar::removeMessage ( medMessage* message )
 {
     if ( message )
     {
-        this->messageList.removeFirst();
-        this->availableSpace += (message->size().width()+d->statusBarLayout->spacing());         //update available space
+        d->listsofMsgMutex.lock();
+        d->messageList.removeFirst();
+        d->listsofMsgMutex.unlock();
```
Comment (mathildemerle) [inline src/layers/legacy/medCoreLegacy/gui/commonWidgets/medStatusBar.cpp:148]: can you unlock after the space computation? As done in addMessage and hideMessage? In addMessage it's even done after the insertion of the widget

File: src/layers/legacy/medCoreLegacy/gui/commonWidgets/medStatusBar.cpp (hunk 2 above)
Comment (ocommowi) [reply src/layers/legacy/medCoreLegacy/gui/commonWidgets/medStatusBar.cpp:181]: Ah ok. Ben dans ce cas, lock le mutex dans le if comme ca tu peux virer le else

Comment (Florent2305) [reply src/layers/legacy/medCoreLegacy/gui/commonWidgets/medStatusBar.cpp:181]: En fait si je l'ai fait avant le if c'est car dans le teste même du if on accède à la liste qui doit être protégée.
J'ai hélas vraiment pas eu  le choix de faire autrement.
Le Else je l'ai pas fait de gaieté de cœur hélas.

File: src/layers/legacy/medCoreLegacy/gui/commonWidgets/medStatusBar.cpp (hunk 3 above)
Comment (fcollot) [reply src/layers/legacy/medCoreLegacy/gui/commonWidgets/medStatusBar.cpp:148]: Mutexes must be unlocked as soon as possible to avoid unnecessary pauses in execution for the other threads waiting on this mutex.

File: src/layers/legacy/medCoreLegacy/gui/commonWidgets/medStatusBar.cpp (hunk 2 above)
Comment (fcollot) [reply src/layers/legacy/medCoreLegacy/gui/commonWidgets/medStatusBar.cpp:181]: Tu peux utiliser un `recursive_mutex` ce qui te permettrait sortir le unlock du if.

File: src/layers/legacy/medCoreLegacy/gui/commonWidgets/medStatusBar.cpp (hunk 3 above)
Comment (Florent2305) [reply src/layers/legacy/medCoreLegacy/gui/commonWidgets/medStatusBar.cpp:148]: @fcollot it's my point of view also
But @mathildemerle makes me notice that we can protect the `availableSpace `
I actually study if availableSpace concurrent access can create a graphical glitch...
@fcollot have you got an opinion about it ?

Comment (fcollot) [reply src/layers/legacy/medCoreLegacy/gui/commonWidgets/medStatusBar.cpp:148]: In my first comment I was taking into account the fact that the goal of the mutex, as stated by its name, is to protect access to the message list only. It is true though that to avoid graphical glitches you could extend the protection and maybe in that case it would be simpler to do something like synchronized methods in java and systematically protect the whole body of the methods in this class (with recursive mutexes). There will no noticeable performance hit since messages will be sent at a much lower rate than what the multithreaded execution can handle.

Comment (fcollot) [reply src/layers/legacy/medCoreLegacy/gui/commonWidgets/medStatusBar.cpp:148]: (so my first message was more of a general best practices comment, not specifically related to the fact there is no real critical performance issue here)

Comment (Florent2305) [reply src/layers/legacy/medCoreLegacy/gui/commonWidgets/medStatusBar.cpp:148]: Of course, I will evolve the mutex name if the goal of mutex extends.
I'm totally agree with the best practice you highlight.
I think your approche is good.
Normally I refrain from using recursive mutex. Few perform and often symptomatic of poor design. As explained in the post https://stackoverflow.com/questions/14498892/stdmutex-vs-stdrecursive-mutex-as-class-member/28741305
But there, it is true that in any case the disgne was not thought for , and that the problems of preformance are so far ...
So I think I'm going to make an exception to my rule;)

Comment (fcollot) [reply src/layers/legacy/medCoreLegacy/gui/commonWidgets/medStatusBar.cpp:148]: Thank you for the link. I agree that you can avoid recursive mutexes by redesigning the code. On the other hand, I have noticed that most of the questions asked on stack overflow (or similar forums) are answered by something like "why do you want to do that, it is bad design". This is especially true for Python questions 😄.

File: src/layers/legacy/medCoreLegacy/gui/commonWidgets/medStatusBar.cpp (hunk 1 above)
Comment (mathildemerle) [reply src/layers/legacy/medCoreLegacy/gui/commonWidgets/medStatusBar.cpp:35]: You forgot to remove this line ^^

File: src/layers/legacy/medCoreLegacy/gui/commonWidgets/medStatusBar.cpp (hunk 3 above)
Comment (mathildemerle) [reply src/layers/legacy/medCoreLegacy/gui/commonWidgets/medStatusBar.cpp:148]: the unlock() still could be moved after the next line to avoid bugs with the available space computation

File: src/layers/legacy/medCoreLegacy/gui/commonWidgets/medStatusBar.cpp (hunk 2 above)
Comment (Florent2305) [reply src/layers/legacy/medCoreLegacy/gui/commonWidgets/medStatusBar.cpp]: done

File: src/layers/legacy/medCoreLegacy/gui/commonWidgets/medStatusBar.cpp (hunk 1 above)
Comment (Florent2305) [reply src/layers/legacy/medCoreLegacy/gui/commonWidgets/medStatusBar.cpp]: done

File: src/layers/legacy/medCoreLegacy/gui/commonWidgets/medStatusBar.cpp (hunk 3 above)
Comment (Florent2305) [reply src/layers/legacy/medCoreLegacy/gui/commonWidgets/medStatusBar.cpp]: done

**Review by mathildemerle — APPROVED** [review]
