### PR TITLE
[Reslice] solve crashs after removing a data in view

### LINKED ISSUE #916: [Reslice] crash trying to start without data after start/close
On Reslice:
 * Open a data
 * Start, Stop
 * Close the data
 * Try to start again: crash

### LINKED ISSUE #920: [Reslice+otherTlbx] crash switching to an other toolbox after removal of data
How to create the crash:
 * In Reslice open a data, and remove it
 * Switch to an other toolbox: crash

```bash
Erreur de segmentation (core dumped)
```

### PR DESCRIPTION
**Pull request by mathildemerle**
A 1-line PR which:
* fix #920 
* fix #916

The removal of the data in the view did not reset the currentView variable.

PS: linked to https://github.com/medInria/medInria-public/pull/921

:m:

### CODE REVIEW

File: src/plugins/legacy/reformat/resliceToolBox.cpp [hunk 1]
```diff
@@ -263,6 +263,7 @@ void resliceToolBox::updateView()
 {
     medAbstractView* view = this->getWorkspace()->tabbedViewContainers()->getFirstSelectedContainerView();
 
+    d->currentView = nullptr;
     if (view && d->currentView!= view)
```
Comment (fcollot) [inline src/plugins/legacy/reformat/resliceToolBox.cpp:267]: The second part of this test should be removed

Comment (mathildemerle) [reply src/plugins/legacy/reformat/resliceToolBox.cpp]: Indeed, it's done, i'm going to add this change to the other PR also
