### PR TITLE
Mesh bug

### LINKED ISSUE #398: Disparition lors de combinaison image 3D et mesh
Quand on ouvre une image 3D puis un mesh vtk, si on supprime l'image 3D on a plus rien.

### LINKED ISSUE #474: Tensor view crash
I have found a crashing bug on the current version of medInria. Drop a raw DWI image, then a tensor image extracted from it. And then the app crashes !

Here is the log I have on Mac

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libmedVtkInria.dylib          	0x00000001172c08bd vtkImageView2D::GetSliceRange(int&, int&) const + 109
1   libmedVtkInria.dylib          	0x00000001172cd92a vtkImageViewCornerAnnotation::TextReplace(vtkImageActor*, vtkImageMapToWindowLevelColors*) + 1882
2   libmedVtkInria.dylib          	0x00000001172cf1b8 vtkImageViewCornerAnnotation::RenderOpaqueGeometry(vtkViewport*) + 632
3   libvtkRenderingCore-8.1.1.dylib	0x00000001173d3ed7 vtkRenderer::UpdateOpaquePolygonalGeometry() + 55
4   libvtkRenderingOpenGL2-8.1.1.dylib	0x000000011878d7da vtkOpenGLRenderer::UpdateGeometry() + 1626
5   libvtkRenderingOpenGL2-8.1.1.dylib	0x000000011878d152 vtkOpenGLRenderer::DeviceRender() + 178
6   libvtkRenderingCore-8.1.1.dylib	0x00000001173d2d74 vtkRenderer::Render() + 1252
7   libvtkRenderingCore-8.1.1.dylib	0x00000001173d1d09 vtkRendererCollection::Render() + 137
8   libvtkRenderingCore-8.1.1.dylib	0x00000001173dd49c vtkRenderWindow::DoStereoRender() + 140
9   libvtkRenderingCore-8.1.1.dylib	0x00000001173dc779 vtkRenderWindow::Render() + 649
10  libvtkRenderingOpenGL2-8.1.1.dylib	0x00000001187256e2 vtkGenericOpenGLRenderWindow::Render() + 34
11  libvtkRenderingCore-8.1.1.dylib	0x00000001173e0567 vtkRenderWindowInteractor::Render() + 39
12  org.qt-project.QtCore         	0x0000000110bf21bf QMetaObject::activate(QObject*, int, int, void**) + 2319
13  libmedCoreLegacy.dylib        	0x000000010f28c5fc medAbstractBoolParameterL::valueChanged(bool) + 60
14  org.qt-project.QtCore         	0x0000000110bf21bf QMetaObject::activate(QObject*, int, int, void**) + 2319
15  org.qt-project.QtWidgets      	0x000000010f5f080a QAbstractButtonPrivate::emitToggled(bool) + 106
16  org.qt-project.QtWidgets      	0x000000010f5efc22 QAbstractButton::setChecked(bool) + 242
17  libmedCoreLegacy.dylib        	0x000000010f1c1f04 medAbstractLayeredViewInteractor::visibilityParameter() + 580
18  libitkDataTensorImagePlugin.dylib	0x000000011d57ea52 itkDataTensorImageVtkViewInteractor::setInputData(medAbstractData*) + 3026
19  libmedCoreLegacy.dylib        	0x000000010f1c2e24 medAbstractImageView::initialiseInteractors(medAbstractData*) + 868
20  libmedCoreLegacy.dylib        	0x000000010f1c86ad medAbstractLayeredView::insertLayer(unsigned int, medAbstractData*) + 445
21  libmedCoreLegacy.dylib        	0x000000010f1d5b04 medViewContainer::addData(medAbstractData*) + 116
22  libmedCoreLegacy.dylib        	0x000000010f1d6b00 medViewContainer::dataReady(medDataIndex, QUuid) + 240
23  libmedCoreLegacy.dylib        	0x000000010f2970a1 0x10f1a1000 + 1007777
24  org.qt-project.QtCore         	0x0000000110bf21bf QMetaObject::activate(QObject*, int, int, void**) + 2319
25  libmedCoreLegacy.dylib        	0x000000010f289971 0x10f1a1000 + 952689
26  org.qt-project.QtCore         	0x0000000110bf21bf QMetaObject::activate(QObject*, int, int, void**) + 2319
27  libmedCoreLegacy.dylib        	0x000000010f28906c 0x10f1a1000 + 950380
28  org.qt-project.QtCore         	0x0000000110beaba1 QObject::event(QEvent*) + 753
29  org.qt-project.QtWidgets      	0x000000010f5079fd QApplicationPrivate::notify_helper(QObject*, QEvent*) + 269
30  org.qt-project.QtWidgets      	0x000000010f508e02 QApplication::notify(QObject*, QEvent*) + 594
31  org.qt-project.QtCore         	0x0000000110bc0cc4 QCoreApplication::notifyInternal2(QObject*, QEvent*) + 212
32  org.qt-project.QtCore         	0x0000000110bc1efe QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) + 878
33  libqcocoa.dylib               	0x0000000112ce9009 QCocoaEventDispatcherPrivate::processPostedEvents() + 313
34  libqcocoa.dylib               	0x0000000112ce9778 QCocoaEventDispatcherPrivate::postedEventsSourceCallback(void*) + 40
35  com.apple.CoreFoundation      	0x00007fff3854ca21 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
36  com.apple.CoreFoundation      	0x00007fff3854c9c0 __CFRunLoopDoSource0 + 103
37  com.apple.CoreFoundation      	0x00007fff3852ff84 __CFRunLoopDoSources0 + 209
38  com.apple.CoreFoundation      	0x00007fff3852f590 __CFRunLoopRun + 1272
39  com.apple.CoreFoundation      	0x00007fff3852ee13 CFRunLoopRunSpecific + 499
40  com.apple.HIToolbox           	0x00007fff370bbb2d RunCurrentEventLoopInMode + 292
41  com.apple.HIToolbox           	0x00007fff370bb86d ReceiveNextEventCommon + 600
42  com.apple.HIToolbox           	0x00007fff370bb5f7 _BlockUntilNextEventMatchingListInModeWithFilter + 64
43  com.apple.AppKit              	0x00007fff35751ac4 _DPSNextEvent + 990
44  com.apple.AppKit              	0x00007fff35750834 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1352
45  com.apple.AppKit              	0x00007fff3574afd4 -[NSApplication run] + 658
46  libqcocoa.dylib               	0x0000000112ce84f3 QCocoaEventDispatcher::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 2579
47  org.qt-project.QtCore         	0x0000000110bbc13f QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 431
48  org.qt-project.QtCore         	0x0000000110bc12d2 QCoreApplication::exec() + 130
49                                	0x000000010eba2d1e main + 6046
50  libdyld.dylib                 	0x00007fff6f82e405 start + 1

### PR DESCRIPTION
**Pull request by Florent2305**
Partial Fix #398
Fix #474

### CODE REVIEW

File: src/layers/legacy/medVtkInria/vtkImageView/vtkImageView3D.cxx [hunk 1]
```diff
@@ -965,7 +963,7 @@ unsigned int vtkImageView3D::GetCroppingMode()
 
 //----------------------------------------------------------------------------
 /**
- The wolrd is not always what we think it is ...
+ The worldb is not always what we think it is ...
```
Comment (mathildemerle) [inline src/layers/legacy/medVtkInria/vtkImageView/vtkImageView3D.cxx]: *world ^^
